name: Check & fix styling

on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
  push:
    branches:
      - master
      - '*.x'

jobs:
  pint:
    runs-on: ubuntu-22.04
    if: ${{ (github.event_name != 'issue_comment') || (github.event.issue.pull_request && contains(github.event.comment.body, '⚡️')) }}

    steps:
      - name: Get latest commit SHA
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        run: |
          echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        with:
          sha: ${{ env.HEAD_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: pint

      - name: Run Laravel Pint
        run: pint --preset laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling

      - name: Set commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        with:
          sha: ${{ env.HEAD_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
