name: Larastan Static Analysis

on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
  push:
    branches:
      - master
      - '*.x'

jobs:
  larastan:
    runs-on: ubuntu-22.04
    if: ${{ (github.event_name != 'issue_comment') || (github.event.issue.pull_request && contains(github.event.comment.body, '⚡️')) }}

    steps:
      - name: Get latest commit SHA
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        run: |
          echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        with:
          sha: ${{ env.HEAD_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Larastan
        run: vendor/bin/phpstan

      - name: Set commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '⚡️') }}
        with:
          sha: ${{ env.HEAD_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
