name: Larastan Static Analysis

on:
  issue_comment:
    types:
      - created
      - edited
  push:
    branches:
      - master
      - '*.x'
  schedule:
    - cron: '0 0 * * *'

jobs:
  larastan:
    runs-on: ubuntu-22.04
    if: ${{ (github.event_name != 'issue_comment') || (github.event.issue.pull_request && contains(github.event.comment.body, '⚡️')) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Larastan
        run: vendor/bin/phpstan
