name: Validate Core Generator Styling

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

jobs:
  validator:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'

    strategy:
      fail-fast: true
      matrix:
        variants: [
          '',
          '--without-rate-limiting',
          '--kind username-based',
          '--kind username-based --without-rate-limiting'
        ]

    name: Variant - ${{ matrix.variants }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./monorepo

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2, pint
          coverage: none

      - name: Create Laravel Project
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer create-project laravel/laravel app "10.x" --remove-vcs --prefer-dist --no-interaction

      - name: Relax dependency constraint for claudiodekker/laravel-auth-core
        run: |
          sed -i "s/\"claudiodekker\/laravel-auth-core\": \".*\"/\"claudiodekker\/laravel-auth-core\": \"\*\"/" composer.json
        working-directory: ./monorepo/packages/bladebones

      - name: Install Library & Bladebones Adapter
        run: |
          composer config minimum-stability dev
          composer config repositories.library path ../monorepo/packages/core
          composer config repositories.adapter path ../monorepo/packages/bladebones
          composer require claudiodekker/laravel-auth-core claudiodekker/laravel-auth-bladebones
        working-directory: ./app

      - name: Generate Auth Scaffolding
        run: php artisan auth:generate --yes ${{ matrix.variants }}
        working-directory: ./app

      - name: Stage all generated files
        run: |
          git config --global user.email "github@actions.test"
          git config --global user.name "GitHub Actions"
          git init .
          git add .
          git commit -m "Generated Auth Scaffolding"
        working-directory: ./app

      - name: Fix using Laravel Pint
        run: pint --preset laravel
        working-directory: ./app

      - name: Show any to-be-fixed changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
              exit 0
          fi

          git -c color.ui=always --no-pager diff
          exit 1
        working-directory: ./app
